### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by WilliamLCobb** [wjlafrance/bnetclient#1]
Just wondering if you have any idea how applicable this is to the current Battle Net protocol. I assume it is going to take a bunch of fixes to make it work again but I'm curious if you have any additional information that could help before I pick up where you left off.

**Comment by wjlafrance** [comment]
Hey @WilliamLCobb, thanks for writing.

This client uses the original Battle.net protocol, not the 2.0 protocol used by World of Warcraft, Diablo 3, and StarCraft 2.

Recently StarCraft 1 was patched and now uses an entirely new protocol, so this client can definitely not emulate StarCraft (STAR, SEXP, JSTR clients). I don't think it ever supported WarCraft 3 (WAR3, W3XP clients). However, it should still work with Diablo II (D2DV and D2XP clients) as well as WarCraft II (W2BN client). I haven't tested it recently, but I don't know why it wouldn't work with a valid BNLS server.

**Comment by WilliamLCobb** [comment]
Thank you so much for the reply. Seems like I have a lot of work to do.

Last question. A quick google search didn't turn up much on the specifics of the 2.0 protocol. Are you aware of anyone that has made progress reversing it?

**Comment by wjlafrance** [comment]
[This](https://bnetdocs.org/document/32/battle-net-v2-information) might be able to send you in the right direction. I haven't looked too much at the protocol myself.

Also, StarCraft 1.18 is using an encrypted, websocket-based protocol which is not Battle.net 2.0. I'm calling it "Battle.net 1.1".

I agree with your assessment about having a lot of work to do. :P If you're looking to connect to Bnet2, this project probably is not a good starting place, to be honest. Very little work will carry over.

**Comment by WilliamLCobb** [comment]
That's perfect, thanks. And yea this will definitely be a challenge but should be pretty fun, especially if I can get something to work. I'm hoping that understanding the 1.0 protocol will help in decoding 2.0, even if the code doesn't carry over.

Thanks again for the help.
